version: "3.4"
services:
  server:
    image: sailing-app
    container_name: sailing-app_app
    ports:
      - "8086:8086"
    depends_on:
      - db
  db:
    image: postgres:14-bullseye
    container_name: sailing-app_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sailing-app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    name: sailing-app_postgres